import axios from 'axios'

axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
axios.defaults.xsrfCookieName = "csrftoken";
/**
 * This function is called to send the user's files to the server, where the ML code runs to generate the heatmaps
 * @param {formData} formData 
 * @returns the modelID of the model generated by the ML python backend
 */
async function uploadRequest(formData) {
    let res = await axios.post('http://127.0.0.1:8000/upload/request', formData, {
        headers: {
            'Content-Type': 'multipart/form-data'
        },
    });
    return res.data
}
export default uploadRequest